datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      version: 1
      url: http://prometheus-server:80
      access: proxy
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    pod-dashboard:
      url: https://karpenter.sh/preview/getting-started/karpenter-pod-metrics.json
    node-dashboard:
      url: https://karpenter.sh/preview/getting-started/karpenter-node-metrics.json
